"""add price and ingredient columns to menus

Revision ID: 07fe00076dca
Revises: a67fbf914d72
Create Date: 2025-12-17 18:44:59.712679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fe00076dca'
down_revision: Union[str, Sequence[str], None] = 'a67fbf914d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('menus', sa.Column('list_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('menus', sa.Column('main_ingredient', sa.String(length=100), nullable=True))
    op.drop_column('menus', 'base_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('menus', 'main_ingredient')
    op.drop_column('menus', 'list_price')
    op.drop_column('menus', 'cost_price')
    # ### end Alembic commands ###
