"""add_manuals_table

Revision ID: 4a2bb61e2465
Revises: 123d3f1dbe4a
Create Date: 2025-12-22 18:32:01.034424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '4a2bb61e2465'
down_revision: Union[str, Sequence[str], None] = '123d3f1dbe4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manuals',
    sa.Column('manual_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('manual_id')
    )
    op.create_index(op.f('ix_manuals_manual_id'), 'manuals', ['manual_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manuals_manual_id'), table_name='manuals')
    op.drop_table('manuals')
    # ### end Alembic commands ###
