"""add_store_inquiries_table

Revision ID: 71461bb8676c
Revises: 4a2bb61e2465
Create Date: 2025-12-22 19:14:14.736563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71461bb8676c'
down_revision: Union[str, Sequence[str], None] = '4a2bb61e2465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_inquiries',
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('inquiry_id')
    )
    op.create_index(op.f('ix_store_inquiries_inquiry_id'), 'store_inquiries', ['inquiry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_inquiries_inquiry_id'), table_name='store_inquiries')
    op.drop_table('store_inquiries')
    # ### end Alembic commands ###
