"""Split review analysis table

Revision ID: 925918bf8ee7
Revises: c385ae2098b1
Create Date: 2025-12-17 20:02:40.147367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925918bf8ee7'
down_revision: Union[str, Sequence[str], None] = 'c385ae2098b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('marketing_strategy', sa.Text(), nullable=True),
    sa.Column('operational_improvement', sa.Text(), nullable=True),
    sa.Column('risk_assessment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_store_reports_report_id'), 'store_reports', ['report_id'], unique=False)
    op.create_table('review_analysis',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('classification', sa.JSON(), nullable=True),
    sa.Column('ai_reply', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], ),
    sa.PrimaryKeyConstraint('analysis_id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_index(op.f('ix_review_analysis_analysis_id'), 'review_analysis', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_analysis_analysis_id'), table_name='review_analysis')
    op.drop_table('review_analysis')
    op.drop_index(op.f('ix_store_reports_report_id'), table_name='store_reports')
    op.drop_table('store_reports')
    # ### end Alembic commands ###
