"""add menus table

Revision ID: a67fbf914d72
Revises: 98714a09d39b
Create Date: 2025-12-17 18:31:03.298282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67fbf914d72'
down_revision: Union[str, Sequence[str], None] = '98714a09d39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('menu_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_seasonal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_menus_menu_id'), 'menus', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menus_menu_name'), 'menus', ['menu_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_menu_name'), table_name='menus')
    op.drop_index(op.f('ix_menus_menu_id'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
