"""Add sales_daily table

Revision ID: a9f0e037c87b
Revises: a9f5b1ae7dd7
Create Date: 2025-12-17 19:34:43.513383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f0e037c87b'
down_revision: Union[str, Sequence[str], None] = 'a9f5b1ae7dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_daily',
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('sales_id'),
    sa.UniqueConstraint('store_id', 'sale_date', name='uix_store_date')
    )
    op.create_index(op.f('ix_sales_daily_sales_id'), 'sales_daily', ['sales_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_daily_sales_id'), table_name='sales_daily')
    op.drop_table('sales_daily')
    # ### end Alembic commands ###
