"""Add pgvector and embeddings

Revision ID: c385ae2098b1
Revises: a9f0e037c87b
Create Date: 2025-12-17 19:47:18.472476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c385ae2098b1'
down_revision: Union[str, Sequence[str], None] = 'a9f0e037c87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_categories_category_id'),
                  table_name='complaint_categories')
    op.drop_table('complaint_categories')
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('menus', sa.Column(
        'description', sa.String(length=500), nullable=True))
    op.add_column('menus', sa.Column('embedding', Vector(1536), nullable=True))
    op.add_column('reviews', sa.Column(
        'embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'embedding')
    op.drop_column('menus', 'embedding')
    op.drop_column('menus', 'description')
    op.create_table('complaint_categories',
                    sa.Column('category_id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('category_name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'category_id', name=op.f('complaint_categories_pkey'))
                    )
    op.create_index(op.f('ix_complaint_categories_category_id'),
                    'complaint_categories', ['category_id'], unique=False)
    # ### end Alembic commands ###
